### ISSUE TITLE
Log::ger::Layout::Pattern: Custom caller depth offset

### ISSUE THREAD

**Issue by sesc** [perlancar/perl-Log-ger#1]
When using a module with a sub that calls my custom code, I wish to ignore that module in the trace elements available in Log::ger::Layout::Pattern output.

My typical use case where this is relevant is Try::Tiny.
With Log::Log4perl:
>#!/usr/bin/env perl
>package Log4perl_demo;
>use strict; use warnings;
>use Log::Log4perl ':easy';
>Log::Log4perl->easy_init( {
>    level  => $DEBUG,
>    layout => '[%C:%M:%L] %m {%F}%n',
>} );
>use Try::Tiny;
>try {
>    WARN "foo";
>};

Output:
> [Log4perl_demo:Log4perl_demo::try {...} :11] foo {./log4perl_demo.pl}

With Log::ger:
>#!/usr/bin/env perl
>package Logger_demo;
>use strict; use warnings;
>use Log::ger;
>use Log::ger::Layout ( Pattern => (format => '[%C:%M:%L] %m {%F}') );
>use Log::ger::Output 'Screen';
>use Try::Tiny;
>
>try {
>    $Log::ger::Caller_Depth_Offset = 2; #<--[1]
>    log_warn "bar";
>};

Output WITHOUT the line marked [1]:
> [Try::Tiny:try {...} :10] bar {/usr/local/share/perl/5.22.1/Try/Tiny.pm}

Output WITH the line marked [1] ("2" because try() in turn calls an eval, adding another frame):
> [Logger_demo:try:93] bar {./logger_demo.pl}

$Log::ger::Caller_Depth_Offset seems like a promising solution pathway. But:
1. I am looking for an on-import facility to configure "always ignore module XY in log traces". Have I missed anything in the docs? If not, could this be added?
2. Note that the line number is correct without the "hack", incorrect with it.

**Comment by perlancar** [comment]
The option to ignore modules A,B,C,... in stack trace would be useful indeed, and more flexible than the Caller_Depth_Offset approach. The option is not there yet, I'll add this soon.

**Comment by perlancar** [comment]
I've released Log::ger::Layout::Pattern 0.003 which implements this. By default I've set the call stack/caller to ignore Try::Tiny. The output should be similar to Log::Log4perl::Layout::PatternLayout now. Please take a look.
