### ISSUE TITLE
Error in DESCRIPTION Documentation

### ISSUE THREAD

**Issue by borisdaeppen** [perlancar/perl-Log-ger#2]
In the following paragraph:

> Low startup overhead. Only ~0.5-1ms. For comparison, strict ~0.2-0.5ms, warnings ~2ms, Log::Any 0.15 ~2-3ms, Log::Any 1.049 ~8-10ms, Log::Log4perl ~35ms. This is measured on a 2014-2015 PC and before doing any output configuration. I strive to make use Log::ger; statement to be roughly as light as use strict; or use warnings; so the impact of adding the statement is really minimal and you can just add logging without much thought to most of your modules. This is important to me because I want logging to be pervasive.

This part seems to be an error or typo, because the same module is mentioned twice:

> Log::Any 0.15 ~2-3ms, Log::Any 1.049 ~8-10ms

Since it is not obvious how to fix it, I'll leaf it at that and just mention it here.

**Comment by perlancar** [comment]
It's not a typo, they are two versions of the same module. I'll add a "v" prefix to make it clearer.
